import type { Metadata } from "next";
import {  Geist_Mono } from "next/font/google";
import { Chivo } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import SlantedLine from "./components/ux_helpers/SlantedLine";


// Configure Chivo font
const chivo = Chivo({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-chivo",
  display: "swap",
});
 

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${chivo.variable} ${geistMono.variable} overflow-x-hidden`}>
      <body className={`antialiased flex font-sans h-full `}>
        <SlantedLine/>
      
            <SideBar />

       

        {children}


        
      </body>
    </html>
  );
}